# Generated by Django 3.0.2 on 2021-05-02 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.CharField(max_length=10, verbose_name='学年')),
            ],
            options={
                'verbose_name_plural': '学習学年',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons', models.CharField(max_length=5, verbose_name='前期or後期')),
            ],
            options={
                'verbose_name_plural': '前期or後期',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=10, unique=True, verbose_name='講義名')),
                ('subinfo', models.TextField(blank=True, null=True, verbose_name='講義内容の紹介')),
            ],
            options={
                'verbose_name_plural': '科目名を登録(例:薬理学序論\u3000薬理学1 ・・・)',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works', models.CharField(max_length=25, verbose_name='刺激・遮断・酵素阻害等')),
            ],
            options={
                'verbose_name_plural': '作用の仕方',
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=25, unique=True, verbose_name='分野名(科目)\u3000例：中枢神経(薬理Ⅰ)\u3000')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yakuri.Subject', verbose_name='科目選択')),
            ],
            options={
                'verbose_name_plural': '分野名登録',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='薬物名')),
                ('target', models.CharField(max_length=35, verbose_name='標的受容体・標的タンパク')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='特徴・説明')),
                ('structure', models.ImageField(blank=True, null=True, upload_to='image')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yakuri.Fields', verbose_name='分野(科目)選択')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yakuri.Grade', verbose_name='学年')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yakuri.Season', verbose_name='学期')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yakuri.Work', verbose_name='作用の仕方')),
            ],
            options={
                'verbose_name_plural': '医薬品の名前・作用・学習時期・構造式の登録',
            },
        ),
        migrations.AddConstraint(
            model_name='fields',
            constraint=models.UniqueConstraint(fields=('subject', 'fields'), name='subjects_fields_unique'),
        ),
        migrations.AddConstraint(
            model_name='detail',
            constraint=models.UniqueConstraint(fields=('field', 'name'), name='field_name'),
        ),
    ]
