# Generated by Django 3.0.2 on 2021-05-15 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='studynum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='表示順序'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='fieldsnum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='目次順番'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectsnum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='科目ナンバー'),
        ),
        migrations.AlterField(
            model_name='target',
            name='targetsnum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='作用点表示順'),
        ),
        migrations.AlterField(
            model_name='work',
            name='worknum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='作用分類の順序'),
        ),
    ]
