# Generated by Django 3.0.2 on 2021-05-05 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='fieldsnum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)], verbose_name='目次の順番'),
        ),
        migrations.AddField(
            model_name='target',
            name='phsiologic',
            field=models.TextField(blank=True, null=True, verbose_name='受容体の生理機能'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='studynum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)], verbose_name='表示順序'),
        ),
    ]
