# Generated by Django 3.0.2 on 2021-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='descriptione',
            field=models.TextField(blank=True, null=True, verbose_name='分野の紹介'),
        ),
    ]
