# Generated by Django 3.0.2 on 2021-05-07 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuri', '0003_auto_20210507_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='worknum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='作用分類の順序'),
        ),
    ]
