# Generated by Django 3.0.2 on 2021-05-07 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuri', '0004_auto_20210507_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjectsnum',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='科目ナンバー'),
        ),
    ]
