# Generated by Django 3.0.2 on 2021-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuri', '0005_subject_subjectsnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='問題文'),
        ),
    ]
